const teste = {
  quiz: {
    id: 1,
    title: 'Quiz Diverso',
    pin: '592905121',
  },
  percentageOfQuizHit: 47.61904761904761,
  questions: [
    {
      avgOfTimeSpentToAnswer: '16.00',
      percentageOfHit: '66.67',
      id: 1,
      title:
        'Normalmente, quantos litros de sangue uma pessoa tem? Em média, quantos são retirados numa doação de sangue?',
      index: 0,
      timer: 30,
      score: 40,
      difficulty_level: 'Muito Difícil',
      type: 'multipleChoice',
      answer: [
        {
          id: 1,
          title: 'Tem entre 2 a 4 litros. São retirados 450 mililitros',
          is_correct: false,
          numberOfChoices: 2,
        },
        {
          id: 2,
          title: 'Tem entre 4 a 6 litros. São retirados 450 mililitros',
          is_correct: true,
          numberOfChoices: 4,
        },
        {
          id: 3,
          title: 'Tem 10 litros. São retirados 2 litros',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 4,
          title: 'Tem 7 litros. São retirados 1,5 litros',
          is_correct: false,
          numberOfChoices: 0,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 2,
          checked1: true,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 12,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 22,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 10,
          checked1: true,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 10,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 28,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
    {
      avgOfTimeSpentToAnswer: '15.67',
      percentageOfHit: '33.33',
      id: 5,
      title: 'De quem é a famosa frase “Penso, logo existo”?',
      index: 1,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 17,
          title: 'Platão',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 18,
          title: 'Galileu Galilei',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 19,
          title: 'Descartes',
          is_correct: true,
          numberOfChoices: 2,
        },
        {
          id: 20,
          title: 'Sócrates',
          is_correct: false,
          numberOfChoices: 2,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 10,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: true,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 21,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: true,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 26,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
    {
      avgOfTimeSpentToAnswer: '13.83',
      percentageOfHit: '50.00',
      id: 2,
      title: 'De onde é a invenção do chuveiro elétrico?',
      index: 2,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 13,
          title: 'França',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 14,
          title: 'Inglaterra',
          is_correct: false,
          numberOfChoices: 1,
        },
        {
          id: 15,
          title: 'Brasil',
          is_correct: true,
          numberOfChoices: 3,
        },
        {
          id: 16,
          title: 'Austrália',
          is_correct: false,
          numberOfChoices: 0,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 18,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 21,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
    {
      avgOfTimeSpentToAnswer: '15.50',
      percentageOfHit: '50.00',
      id: 6,
      title: 'Quantas casas decimais tem o número pi?',
      index: 3,
      timer: 30,
      score: 10,
      difficulty_level: 'Fácil',
      type: 'multipleChoice',
      answer: [
        {
          id: 5,
          title: 'Centenas',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 6,
          title: 'Infinitas',
          is_correct: true,
          numberOfChoices: 3,
        },
        {
          id: 7,
          title: 'Vinte',
          is_correct: false,
          numberOfChoices: 1,
        },
        {
          id: 8,
          title: 'Duas',
          is_correct: false,
          numberOfChoices: 0,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 6,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 23,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 29,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 29,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
    {
      avgOfTimeSpentToAnswer: '14.00',
      percentageOfHit: '50.00',
      id: 3,
      title:
        'Atualmente, quantos elementos químicos a tabela periódica possui?',
      index: 4,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 9,
          title: '113',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 10,
          title: '109',
          is_correct: false,
          numberOfChoices: 1,
        },
        {
          id: 11,
          title: '108',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 12,
          title: '118',
          is_correct: true,
          numberOfChoices: 3,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 14,
          checked1: false,
          checked2: true,
          checked3: false,
          checked4: false,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 24,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: true,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: true,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: true,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
    {
      avgOfTimeSpentToAnswer: '18.50',
      percentageOfHit: '33.33',
      id: 7,
      title: 'Qual o número mínimo de jogadores numa partida de futebol?',
      index: 5,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 25,
          title: '8',
          is_correct: false,
          numberOfChoices: 1,
        },
        {
          id: 26,
          title: '9',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 27,
          title: '7',
          is_correct: true,
          numberOfChoices: 3,
        },
        {
          id: 28,
          title: '10',
          is_correct: false,
          numberOfChoices: 1,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 5,
          checked1: true,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 7,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 28,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: true,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
    {
      avgOfTimeSpentToAnswer: '18.17',
      percentageOfHit: '50.00',
      id: 4,
      title:
        'Qual era o nome do tratado que a Alemanha foi obrigada a assinar após a Primeira Guerra Mundial, que limitava seus poderes e a considerava a única culpada pelo conflito?',
      index: 6,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 21,
          title: 'Tratado de Amsterdã',
          is_correct: false,
          numberOfChoices: 1,
        },
        {
          id: 22,
          title: 'Tratado de Badajós',
          is_correct: false,
          numberOfChoices: 0,
        },
        {
          id: 23,
          title: 'Tratado de Versalhes',
          is_correct: true,
          numberOfChoices: 3,
        },
        {
          id: 24,
          title: 'Tratado de Tordesilhas',
          is_correct: false,
          numberOfChoices: 0,
        },
      ],
      question_choice: [
        {
          student_quiz_id: 1,
          student_id: 1,
          time_left: 3,
          checked1: true,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'celso',
            email: 'celso@gmail.com',
          },
        },
        {
          student_quiz_id: 3,
          student_id: 2,
          time_left: 12,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'kamilinhna',
            email: 'kamilicunha@hotmail.com',
          },
        },
        {
          student_quiz_id: 25,
          student_id: 4,
          time_left: 29,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Marcos Silvano',
            email: 'marcos@gmail.com',
          },
        },
        {
          student_quiz_id: 41,
          student_id: 6,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'testenildo',
            email: 'teste@aluno.com',
          },
        },
        {
          student_quiz_id: 43,
          student_id: 7,
          time_left: 0,
          checked1: false,
          checked2: false,
          checked3: false,
          checked4: false,
          student: {
            name: 'vazonildo',
            email: 'taaaa@aluno.com',
          },
        },
        {
          student_quiz_id: 46,
          student_id: 3,
          time_left: 27,
          checked1: false,
          checked2: false,
          checked3: true,
          checked4: false,
          student: {
            name: 'Jhonatan',
            email: '123@gmail.com',
          },
        },
      ],
    },
  ],
};

export default teste;
