const teste = {
  questions: [
    {
      id: 1,
      title:
        'Normalmente, quantos litros de sangue uma pessoa tem? Em média, quantos são retirados numa doação de sangue?',
      index: 0,
      timer: 30,
      score: 40,
      difficulty_level: 'Muito Difícil',
      type: 'multipleChoice',
      answer: [
        {
          id: 1,
          title: 'Tem entre 2 a 4 litros. São retirados 450 mililitros',
          is_correct: false,
        },
        {
          id: 2,
          title: 'Tem entre 4 a 6 litros. São retirados 450 mililitros',
          is_correct: true,
        },
        {
          id: 3,
          title: 'Tem 10 litros. São retirados 2 litros',
          is_correct: false,
        },
        {
          id: 4,
          title: 'Tem 7 litros. São retirados 1,5 litros',
          is_correct: false,
        },
      ],
    },
    {
      id: 5,
      title: 'De quem é a famosa frase “Penso, logo existo”?',
      index: 1,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 17,
          title: 'Platão',
          is_correct: false,
        },
        {
          id: 18,
          title: 'Galileu Galilei',
          is_correct: false,
        },
        {
          id: 19,
          title: 'Descartes',
          is_correct: true,
        },
        {
          id: 20,
          title: 'Sócrates',
          is_correct: false,
        },
      ],
    },
    {
      id: 2,
      title: 'De onde é a invenção do chuveiro elétrico?',
      index: 2,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 13,
          title: 'França',
          is_correct: false,
        },
        {
          id: 14,
          title: 'Inglaterra',
          is_correct: false,
        },
        {
          id: 15,
          title: 'Brasil',
          is_correct: true,
        },
        {
          id: 16,
          title: 'Austrália',
          is_correct: false,
        },
      ],
    },
    {
      id: 6,
      title: 'Quantas casas decimais tem o número pi?',
      index: 3,
      timer: 30,
      score: 10,
      difficulty_level: 'Fácil',
      type: 'multipleChoice',
      answer: [
        {
          id: 5,
          title: 'Centenas',
          is_correct: false,
        },
        {
          id: 6,
          title: 'Infinitas',
          is_correct: true,
        },
        {
          id: 7,
          title: 'Vinte',
          is_correct: false,
        },
        {
          id: 8,
          title: 'Duas',
          is_correct: false,
        },
      ],
    },
    {
      id: 3,
      title:
        'Atualmente, quantos elementos químicos a tabela periódica possui?',
      index: 4,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 9,
          title: '113',
          is_correct: false,
        },
        {
          id: 10,
          title: '109',
          is_correct: false,
        },
        {
          id: 11,
          title: '108',
          is_correct: false,
        },
        {
          id: 12,
          title: '118',
          is_correct: true,
        },
      ],
    },
    {
      id: 7,
      title: 'Qual o número mínimo de jogadores numa partida de futebol?',
      index: 5,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 25,
          title: '8',
          is_correct: false,
        },
        {
          id: 26,
          title: '9',
          is_correct: false,
        },
        {
          id: 27,
          title: '7',
          is_correct: true,
        },
        {
          id: 28,
          title: '10',
          is_correct: false,
        },
      ],
    },
    {
      id: 4,
      title:
        'Qual era o nome do tratado que a Alemanha foi obrigada a assinar após a Primeira Guerra Mundial, que limitava seus poderes e a considerava a única culpada pelo conflito?',
      index: 6,
      timer: 30,
      score: 15,
      difficulty_level: 'Médio',
      type: 'multipleChoice',
      answer: [
        {
          id: 21,
          title: 'Tratado de Amsterdã',
          is_correct: false,
        },
        {
          id: 22,
          title: 'Tratado de Badajós',
          is_correct: false,
        },
        {
          id: 23,
          title: 'Tratado de Versalhes',
          is_correct: true,
        },
        {
          id: 24,
          title: 'Tratado de Tordesilhas',
          is_correct: false,
        },
      ],
    },
  ],
  studentQuiz: [
    {
      id: 1,
      name: 'celso',
      email: 'celso@gmail.com',
      student_quiz: {
        id: 1,
        score: 0,
        student_id: 1,
        quiz_question_choice: [
          {
            id: 1,
            time_left: 2,
            question_id: 1,
            checked1: true,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 2,
            time_left: 10,
            question_id: 5,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: true,
          },
          {
            id: 3,
            time_left: 18,
            question_id: 2,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 4,
            time_left: 6,
            question_id: 6,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 5,
            time_left: 14,
            question_id: 3,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 6,
            time_left: 5,
            question_id: 7,
            checked1: true,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 7,
            time_left: 3,
            question_id: 4,
            checked1: true,
            checked2: false,
            checked3: false,
            checked4: false,
          },
        ],
      },
    },
    {
      id: 2,
      name: 'kamilinhna',
      email: 'kamilicunha@hotmail.com',
      student_quiz: {
        id: 3,
        score: 135,
        student_id: 2,
        quiz_question_choice: [
          {
            id: 16,
            time_left: 12,
            question_id: 1,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 17,
            time_left: 21,
            question_id: 5,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: true,
          },
          {
            id: 18,
            time_left: 21,
            question_id: 2,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 19,
            time_left: 23,
            question_id: 6,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 20,
            time_left: 24,
            question_id: 3,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: true,
          },
          {
            id: 21,
            time_left: 7,
            question_id: 7,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 22,
            time_left: 12,
            question_id: 4,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
        ],
      },
    },
    {
      id: 3,
      name: 'Jhonatan',
      email: '123@gmail.com',
      student_quiz: {
        id: 46,
        score: 393,
        student_id: 3,
        quiz_question_choice: [
          {
            id: 164,
            time_left: 28,
            question_id: 1,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 165,
            time_left: 26,
            question_id: 5,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 166,
            time_left: 29,
            question_id: 2,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 167,
            time_left: 29,
            question_id: 6,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 168,
            time_left: 29,
            question_id: 3,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: true,
          },
          {
            id: 169,
            time_left: 28,
            question_id: 7,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: true,
          },
          {
            id: 170,
            time_left: 27,
            question_id: 4,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
        ],
      },
    },
    {
      id: 4,
      name: 'Marcos Silvano',
      email: 'marcos@gmail.com',
      student_quiz: {
        id: 25,
        score: 181,
        student_id: 4,
        quiz_question_choice: [
          {
            id: 108,
            time_left: 22,
            question_id: 1,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 109,
            time_left: 29,
            question_id: 5,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 110,
            time_left: 29,
            question_id: 2,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 111,
            time_left: 29,
            question_id: 6,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 112,
            time_left: 29,
            question_id: 3,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: true,
          },
          {
            id: 113,
            time_left: 29,
            question_id: 7,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
          {
            id: 114,
            time_left: 29,
            question_id: 4,
            checked1: false,
            checked2: false,
            checked3: true,
            checked4: false,
          },
        ],
      },
    },
    {
      id: 6,
      name: 'testenildo',
      email: 'teste@aluno.com',
      student_quiz: {
        id: 41,
        score: 0,
        student_id: 6,
        quiz_question_choice: [
          {
            id: 129,
            time_left: 10,
            question_id: 1,
            checked1: true,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 130,
            time_left: 0,
            question_id: 2,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 131,
            time_left: 0,
            question_id: 3,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 132,
            time_left: 0,
            question_id: 4,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 133,
            time_left: 0,
            question_id: 5,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 134,
            time_left: 0,
            question_id: 6,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 135,
            time_left: 0,
            question_id: 7,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
        ],
      },
    },
    {
      id: 7,
      name: 'vazonildo',
      email: 'taaaa@aluno.com',
      student_quiz: {
        id: 43,
        score: 16,
        student_id: 7,
        quiz_question_choice: [
          {
            id: 143,
            time_left: 10,
            question_id: 1,
            checked1: false,
            checked2: true,
            checked3: false,
            checked4: false,
          },
          {
            id: 144,
            time_left: 0,
            question_id: 2,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 145,
            time_left: 0,
            question_id: 3,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 146,
            time_left: 0,
            question_id: 4,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 147,
            time_left: 0,
            question_id: 5,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 148,
            time_left: 0,
            question_id: 6,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
          {
            id: 149,
            time_left: 0,
            question_id: 7,
            checked1: false,
            checked2: false,
            checked3: false,
            checked4: false,
          },
        ],
      },
    },
  ],
};

export default teste;
