version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: 'db'
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_dev:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SENHA_DO_USUARIO_MYSQL_AQUI
      - MYSQL_PASSWORD=SENHA_DO_BANCO
      - MYSQL_DATABASE=NOME_DO_BANCO
    networks:
      - app-tier 

  backend:
    container_name: 'back_end'
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - db
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=SENHA_DO_BANCO
      - DB_NAME=NOME_DO_BANCO
      - DB_DIALECT=mysql
      - APP_URL=http://localhost:3333
      - PORT=3333
      - SECRET=SECRET_AQUI
      - EXPIRE_IN=DIAS_PARA_EXPIRAR_TOKEN
      - REFRESH_EXPIRATION=    
      - TIMEZONE=+03:00
    networks:
      - app-tier


  frontend:
    container_name: 'front_end'
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    environment:
        - REACT_APP_BASE_URL=http://localhost:3333
    volumes:
      - ./frontend:/home/node/react
      - /home/node/react/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: on-failure
    networks:
      - app-tier
    
  
  