version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db_prod:
    container_name: 'db_prod'
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3308'
    volumes:
      - ./mysql_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=SENHA_DO_USUARIO_MYSQL_AQUI
      - MYSQL_PASSWORD=SENHA_DO_BANCO
      - MYSQL_DATABASE=NOME_DO_BANCO
    networks:
      - app-tier 

  backend_prod:
    container_name: 'backend_prod'
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/home/node/api_prod
      - /home/node/api_prod/node_modules
    ports:
      - '3334:3334'
    depends_on:
      - db_prod
    restart: on-failure
    environment:
      - DB_HOST=db_prod
      - DB_PORT=3308
      - DB_USER=root
      - DB_PASS=SENHA_DO_BANCO
      - DB_NAME=NOME_DO_BANCO
      - DB_DIALECT=mysql
      - APP_URL=http://localhost:3334
      - PORT=3334
      - SECRET=SECRET_AQUI
      - EXPIRE_IN=DIAS_PARA_EXPIRAR_TOKEN
      - REFRESH_EXPIRATION=   
      - TIMEZONE=+03:00
    networks:
      - app-tier

  frontend_prod:
    container_name: 'frontend_prod'
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - API_URL=http://localhost:3334
    volumes:
      - ./frontend:/home/node/react_prod
      - /home/node/react_prod/node_modules
    ports:
      - '80:80'
    depends_on:
      - backend_prod
    restart: on-failure
    networks:
      - app-tier
    
  
  