version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db_prod:
    container_name: 'db_prod'
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3308:3308'
    volumes:
      - ./mysql_prod:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_PASSWORD=123456
      - MYSQL_DATABASE=db_quiz
    networks:
      - app-tier 

  backend_prod:
    container_name: 'backend_prod'
    build: 
      context: ./backend
      dockerfile: Dockerfile.prod
    volumes:
      - ./backend:/home/node/api_prod
      - /home/node/api_prod/node_modules
    ports:
      - '3334:3334'
    depends_on:
      - db_prod
    restart: on-failure
    environment:
      - DB_HOST=db_prod
      - DB_PORT=3308
      - DB_USER=root
      - DB_PASS=123456
      - DB_NAME=db_quiz
      - DB_DIALECT=mysql
      - APP_URL=http://localhost:3334
      - PORT=3334
      - SECRET=SECRET_AQUI
      - EXPIRE_IN=2d
      - REFRESH_EXPIRATION=380
      - TIMEZONE=+03:00
    networks:
      - app-tier

    
  
  