version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    networks:
      - app-tier 

  backend:
    networks:
      - app-tier

  frontend:
    networks:
      - app-tier
    
  
  