version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: 'db'
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./.docker/dbdata:/var/ib/mysql
    environment:
      - MYSQL_DATABASE=db_quiz
      - MYSQL_ROOT_PASSWORD=mortadela1
    networks:
      - app-tier 

  backend:
    container_name: 'back_end'
    command: yarn sequelize db:migrate
    command: yarn start
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/node/api
    ports:
      - '3333:3333'
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASS=mortadela1
      - DB_NAME=db_quiz
      - DB_DIALECT=mysql
    networks:
      - app-tier 

    
  
  