version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: 'db'
    image: mysql:8.0.27
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./mysql_dev:/var/lib/mysql
    env_file:
      - ./mysql.env
    networks:
      - app-tier 

  backend:
    container_name: 'back_end'
    build: 
      context: ./backend
      dockerfile: Dockerfile.dev
    volumes:
      - ./backend:/home/node/api
      - /home/node/api/node_modules
    ports:
      - '3333:3333'
    depends_on:
      - db
    restart: on-failure
    env_file:
      - ./backend/.env
    networks:
      - app-tier


  frontend:
    container_name: 'front_end'
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - ./frontend/.env
    volumes:
      - ./frontend:/home/node/react
      - /home/node/react/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - backend
    restart: on-failure
    networks:
      - app-tier
    
  
  