version: '3'

networks:
  app-tier:
    driver: bridge

services:
  db:
    container_name: 'db'
    image: mysql:8.0.25
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3307:3306'
    volumes:
      - ./.docker/dbdata:/var/ib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=quizutfpr
      - MYSQL_PASSWORD=quizutfpr
      - MYSQL_DATABASE=db_quiz_prod
    networks:
      - app-tier 

  backend:
    container_name: 'back_end'
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/home/node/api
    ports:
      - '3333:3333'
    depends_on:
      - db
    restart: on-failure
    environment:
      - DB_HOST=db
      - DB_PORT=3307
      - DB_USER=root
      - DB_PASS=quizutfpr
      - DB_NAME=db_quiz_prod
      - DB_DIALECT=mysql
    networks:
      - app-tier

  frontend:
    container_name: 'front_end'
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    depends_on:
      - backend
    restart: on-failure
    networks:
      - app-tier
    
  
  