FROM node:16.13.0-alpine3.14

RUN apk update && apk add python3 make g++

USER root

RUN mkdir -p /home/node/api_prod/node_modules && chown -R root:root /home/node/api_prod

WORKDIR /home/node/api_prod

COPY --chown=root:root ./package*.json .

RUN yarn install --production=true

COPY --chown=root:root . .

ENV NODE_ENV production

CMD yarn sequelize db:migrate && yarn start:prod

EXPOSE 3334
