FROM node:17.1.0-alpine3.12

RUN mkdir -p /home/node/api/node_modules && chown -R node:node /home/node/api

WORKDIR /home/node/api

COPY ./package*.json .

RUN apk update && apk add python3 make g++

RUN yarn

USER node

COPY --chown=node:node . .

ENV NODE_ENV development

EXPOSE 3333

CMD yarn sequelize db:migrate && yarn start:dev