FROM node:lts-alpine

RUN mkdir -p /home/node/api_prod/node_modules && chown -R node:node /home/node/api_prod

WORKDIR /home/node/api_prod

COPY ./package*.json .

RUN apk update && apk add python3 make g++

RUN yarn install --production=true

USER node

COPY --chown=node:node . .

ENV NODE_ENV production

CMD yarn sequelize db:migrate && yarn start:prod