FROM node:lts-alpine

RUN sudo mkdir -p /home/node/api_prod/node_modules &&  sudo chown -R node:node /home/node/api_prod

WORKDIR /home/node/api_prod

COPY ./package*.json .

RUN sudo apk update && sudo apk add python3 make g++

RUN yarn install --production=true

USER node

COPY --chown=node:node . .

ENV NODE_ENV production

CMD yarn sequelize db:migrate && yarn start:prod