FROM node:16.13.0-alpine3.14

WORKDIR /home/node/api

COPY ./package*.json ./

RUN apk update && apk add python3 make g++

RUN yarn

COPY . .

ENV NODE_ENV development

EXPOSE 3333

CMD yarn sequelize db:migrate && yarn start:dev
