FROM node:lts-alpine

RUN sudo mkdir -p /home/node/api/node_modules && sudo chown -R node:node /home/node/api

WORKDIR /home/node/api

COPY ./package*.json .

RUN sudo apk update && sudo apk add python3 make g++

RUN yarn

USER node

COPY --chown=node:node . .

ENV NODE_ENV development

EXPOSE 3333

CMD yarn sequelize db:migrate && yarn start:dev